<a href="https://colab.research.google.com/github/Ahmed-Ragab/machine-learning-zoomcamp/blob/main/Homework1_ZoomCamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [24]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

## **Pandas** **Version**

In [25]:
pd.__version__

'2.2.2'

**Records count using shape**



In [26]:
df.shape[0]

9704

**How many fuel types are presented in the dataset?**


In [27]:
df['fuel_type'].unique()

array(['Gasoline', 'Diesel'], dtype=object)

**How many columns in the dataset have missing values?**



In [28]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

**What's the maximum fuel efficiency of cars from Asia?**

In [29]:
df[df['origin'] == 'Asia']['fuel_efficiency_mpg'].max()

23.759122836520497

**Find the median value of horsepower column in the dataset**

In [30]:
df['horsepower'].median()

149.0

**Calculate the most frequent value of the same horsepower column**


In [31]:
df['horsepower'].mode()

0    152.0
Name: horsepower, dtype: float64

**Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step**


In [32]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mode())

**Calculate the median value of horsepower once again**

In [33]:
df['horsepower'].median()

149.0

## **Sum of weights**


**Select all the cars from Asia**

**Select only columns vehicle_weight and model_year**

**Select the first 7 values**

In [34]:
asia_cars_weight_year = df[df['origin'] == 'Asia'][['vehicle_weight','model_year']].head(7)

**Get the underlying NumPy array. Let's call it X**

In [35]:
X = np.array(asia_cars_weight_year)
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

**Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.**


In [36]:
XTX = X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

**Invert XTX**

In [37]:
XTX_invert = np.linalg.inv(XTX)
XTX_invert

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

**Create an array y with values**

In [38]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

**Multiply the inverse of XTX with the transpose of X**

In [39]:
z = XTX_invert.dot(X.T)
z

array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
        -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
         4.65094049e-04],
       [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
         6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
        -6.07979633e-04]])

 **Then multiply the result by y. Call the result w**

In [40]:
w = z.dot(y)
w

array([0.01386421, 0.5049067 ])

**What's the sum of all the elements of the result?**

In [41]:
sum_of_w = np.sum(w)
print(f"The sum of all elements in w is: {sum_of_w}")

The sum of all elements in w is: 0.5187709081074016
